### PR TITLE
20250703 13  666 spline transform fails

### LINKED ISSUE #666: Spline.ApplyTransform fails
**The bug**
When a Transform is applied to a spline, an Index-out-of-Range exception occurs.

```
			for (int i = 0; i < this.FitPoints.Capacity; i++)
			{
				this.FitPoints[i] = transform.ApplyTransform(this.FitPoints[i]);
			}
```
`this.FitPoints.Capacity` --> `this.FitPoints.Count`

### PR DESCRIPTION
**Pull request by mme1950**
The for to transform FitPoints must run to Count not to Capacity

Unintended Change of Hatch was rolled back.

fixes #666

### CODE REVIEW

File: src/ACadSharp/Entities/Hatch.cs [hunk 1]
```diff
@@ -156,7 +156,7 @@ public override void ApplyTransform(Transform transform)
 			{
 			}
 
-			throw new NotImplementedException();
+			//	throw new NotImplementedException();
```
Comment (DomCR) [inline src/ACadSharp/Entities/Hatch.cs:159]: Please restore the exception, this is not implemented yet.

**Comment by DomCR** [comment]
Great job!
